modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/CreativeMD/LittleTiles/issues"
license="${mod_license}"

[[mods]]
    modId="littletiles"
    logoFile="littletiles.png"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://modrinth.com/mod/littletiles"
    authors="${mod_authors}"
    description='''${mod_description}'''

[[dependencies.littletiles]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.littletiles]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.littletiles]]
   modId="creativecore"
   mandatory=true
   ordering="NONE"
   side="BOTH"
   versionRange="[2.12.30,)"

